name: Data Vis CI

on:
  - push

jobs:
  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      -
        name: Install node dependencies
        run: npm install -D
      -
        name: Run Tests
        run: npm test

  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      -
        name: Install node dependencies
        run: npm install -D
      -
        name: Build
        run: npm run build
      -
        name: Deploy ðŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
